app:
  feign:
    config:
      name: currencyClient
      url: 'https://api.binance.com/api/v3/ticker/bookTicker'

spring:
  application:
    admin:
      enabled: false

logging:
  level:
    org:
      springframework:
        web: trace
      hibernate: error
    com:
      telegram:
        myBot: debug